___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
np.random.rand(1)

array([0.14226732])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.randn(25)

array([ 0.89512168, -0.07619262,  1.11561315, -0.78265566,  0.01264355,
        1.24250737, -0.53565871,  0.53257343,  0.47883183,  0.88170326,
        0.45932994,  0.5953502 , -0.56975819, -0.82505694,  1.94016936,
       -2.24503939, -0.65254939, -1.50026866, -1.79524017,  0.91712532,
        0.88565418,  1.09421386,  0.31674536,  0.21121404,  0.03080764])

#### Create the following matrix:

In [18]:
np.random.rand(50)

array([0.26478496, 0.50074757, 0.23397146, 0.14394177, 0.4378868 ,
       0.73787754, 0.17225647, 0.67673117, 0.1744183 , 0.74602897,
       0.86845701, 0.47620222, 0.23255035, 0.20975277, 0.16593351,
       0.36865648, 0.41856267, 0.02666353, 0.90998864, 0.26722669,
       0.79806598, 0.7099759 , 0.57920876, 0.89029033, 0.64083692,
       0.27106038, 0.9570001 , 0.15788925, 0.44933648, 0.22573572,
       0.52847388, 0.22787707, 0.39194526, 0.76563306, 0.20384874,
       0.58776837, 0.26699251, 0.57659878, 0.82057395, 0.51602512,
       0.0108832 , 0.14307486, 0.98942901, 0.36596077, 0.77355455,
       0.2419544 , 0.61665381, 0.4944288 , 0.28470555, 0.67320024])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [19]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [21]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
mat[3,4]

20

In [25]:
mat[0:3,1]

array([ 2,  7, 12])

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [28]:
mat[4,:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [29]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [30]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [31]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [33]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!